AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates infrastructure for Safe to Run

Resources:
  SafeToRunBackend:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java11
      CodeUri: SafeToRunBackend/build/libs/SafeToRunBackend-0.1-all.jar
      Description: A function used for verifying a device and returning a signed token
      MemorySize: 1024
      Handler: io.github.dllewellyn.safetorun.backend.handlers.SafeToRunRequestHandler
      Timeout: 120
      FunctionName: SafeToRun

  SafeToRunBackendVerify:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java11
      CodeUri: SafeToRunBackend/build/libs/SafeToRunBackend-0.1-all.jar
      Description: A function used for verifying a device and returning a signed token
      MemorySize: 1024
      Handler: io.github.dllewellyn.safetorun.backend.handlers.SafeToRunVerifyHandler
      Timeout: 120
      FunctionName: SafeToRunVerify
