safe:
  to:
    run:
      jwtsecret: "Changemeplease"
      found_blacklisted_app_check: "Found app %s"
      not_found_blacklisted_app_check: "Not found"
      could_not_find_package: "Could not find package"
      was_not_allowed: "Package was not allowed %s"
      was_allowed: "Package was allowed"
      os_detection_check_generic_failure: "OS detection failed"
      os_detection_check_generic_pass: "OS Detection passed"
      signature_verification: "Signature verification pass"
      signature_verification_failure: "Signature verification failed (%s)"
      signature_verification_not_found: "Signature was not found"

micronaut:
  application:
    name: safeToRunBackend
