name: "Deploy SAM Stack to Production"
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build app 
      run: ./gradlew build shadowJar
    - uses: actions/checkout@v1
    - uses: falnyr/aws-sam-deploy-action@v1.3.0
      env:
        TEMPLATE: 'sam-template.yml'
        AWS_STACK_NAME: sam-safetorun-backend
        AWS_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
