name: "Deploy SAM Stack to Production"
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: ./gradlew shadowJar
    - uses: actions/checkout@v1
    - uses: falnyr/aws-sam-deploy-action@v1.3.0
      env:
        TEMPLATE: 'sam-template.yaml'
        AWS_STACK_NAME: my-serverless-application
        AWS_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
