# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run build & test
        run: ./gradlew build test
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: SafeToRunBackend
          path: SafeToRunBackend/build/libs/SafeToRunBackend-0.1-all.jar
          retention-days: 5
