# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run build & test
        run: ./gradlew build test shadowJar
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: SafeToRunBackend
          path: SafeToRunBackend/build/libs/SafeToRunBackend-0.1-all.jar
          retention-days: 5
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: SafeToRunBackend
      - name: ls
        run: ls -la 
      - uses: falnyr/aws-sam-deploy-action@v1.3.0
        env:
          TEMPLATE: 'sam-template.yml'
          AWS_STACK_NAME: sam-safetorun-backend
          AWS_REGION: 'eu-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
