# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 11
          distribution: corretto
      - uses: actions/checkout@v2
      - name: Run build
        run: ./gradlew build assembleDebug assembleDebugAndroidTest --no-daemon
        env:
          SERVER_URL: 'http://example.com'
          API_KEY: 'apikey'
